[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.gd"]

[phases.install]
cmds = ["echo 'PHP installation completed'"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
